config/routes.rb
Rails.application.routes.draw do
  root to: 'question#create'
  
  #root to: "admin/dashboard#index"
  
  
  get 'question/create'

  get 'question/answer'

  post 'question/store'

  get 'question/retrive'

  devise_for :users# ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_query.rb
class UserQuery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
#  def after_sign_up_path_for(resource_or_scope)
#  	user_confirmation_path
#  end 
#  
#  private
#
#  def current_ability
#    
#   @current_ability ||=  Ability.new(current_user)
#  end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def create
  end

  def answer
  end

  def store
   user_query = UserQuery.new(first_name: params[:first_name],last_name: params[:last_name],phone: params[:contact],email: current_user.email,query: params[:query] )
   user_query.save!
   @answer = []
    if user_query.save!
      
     @answer =  Answer.where("query like ?","%"+params[:query]+"%")
     puts @answer.inspect
    end
  end

  def retrive
    @prev_data= UserQuery.where(email: current_user.email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
          
      
      <% if user_signed_in? %>  
       
      <div style='text-align: right'>
        <br>Hi, <strong><%= current_user.email %></strong>   
      </div>
      <div style='text-align: right'>
        <%= link_to "Active Admin", admin_root_path    %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete,data: { confirm: 'Are you sure?' }   %>
      </div>
      
            <div>
             <nav id="primary_nav_wrap">
               <ul class="current-menu-item">
                   <li><ul><%= link_to "Submit Query",question_create_path() %></ul></li>
               
                   <li><ul><%= link_to "Query List",question_retrive_path() %></ul></li>
               </ul>
             </nav>
            </div>
              

      <% end %>
    <%= yield %>
  </body>
</html>

app/views/question/answer.html.erb
<h1>Question#answer</h1>
<p>Find me in app/views/question/answer.html.erb</p>

app/views/question/create.html.erb
 <%= form_tag(controller: "question", action: 'store', method: "post" ) do %>
    <div class="container" id= "crete_query">
              <div class="panel-group">
                <div class="panel panel-info">
                  <div class="panel-heading"><b>Query Information</b></div>
                  <div class="panel-body">  
                      <table style="width: 60%">
                          <%= hidden_field_tag 'query_uniq_id', Devise.friendly_token %>
                          
                          <tr>
                                <td style="width: 50%"><%=  label_tag 'first_name',"First Name"%></td>
                                <td style="width: 50%"><%= text_field_tag :first_name, nil,:required => true  %></td>                                          
                          </tr>
                          <tr>
                                <td style="width: 50%"><%= label_tag 'last_name',"Last Name"%></td>
                                <td style="width: 50%"><%= text_field_tag :last_name, nil,:required => true %></td>                                          
                          </tr>
                          
                          <tr>
                                <td style="width: 50%"><%= label_tag 'contact',"Contact Number"%></td>
                                <td style="width: 50%"><%= text_field_tag :contact, nil,:required => true %></td>                                          
                          </tr>
                          <tr>
                                <td style="width: 50%"><%= label_tag 'query',"Enter Query"%></td>
                                <td style="width: 50%"><%= text_area_tag :query, nil,:required => true %></td>                                          
                          </tr>

                      </table>  
                  </div>
                </div>
              </div>
                <table>
                    <tr>
                      <td width="20%"> <%= submit_tag("Submit Query") %></td>

                    </tr>
              </table> 
            </div>
<% end %>

app/views/question/retrive.html.erb
<% if @prev_data != nil  %>
<div class="container" id= "retrive_query">
              <div class="panel-group">
                <div class="panel panel-info">
                  <div class="panel-heading"><b>Previous Queries Information</b></div>
                  <div class="panel-body">  
                      <table style="width: 60%">
                            <% @prev_data.each do |prev| %>
                             <tr>
                                <td>                                    
                                   <%=  prev.query %>
                                </td>
                             </tr>
                             <% end %>
                       </table>
                  </div>
                </div>
              </div>
</div>
<% else %>
<h2><b>No Queries yet by you!</b></h2>
<% end %>

<script>
  $(".btn-link").click(function () {
     var id  = this.id;
     alert(id)
</script>

app/views/question/store.html.erb
<% if @answer != []  %>
    <div class="container" id= "crete_query">
                  <div class="panel-group">
                    <div class="panel panel-info">
                      <div class="panel-heading"><b>Solution Information</b></div>
                      <div class="panel-body">
                         <% @answer.each do |ans| %>
                        <table style='width: 60%'>
                          <tr>
                              <td style="width: 50%">Query Mantched by your Pharse is? </td>
                              <td style="width: 50%"><%=  ans.query %></td>
                          </tr>
                          <tr>
                              <td style="width: 50%">Answer </td>
                              <td style="width: 50%"><%=  ans.answer %></td>
                          </tr>
                          <tr>
                              <td style="width: 50%">Solution Provider </td>
                              <td style="width: 50%"><%=  ans.answered_by %></td>
                          </tr>
                          <tr>
                              <td style="width: 50%">Unique ID </td>
                              <td style="width: 50%"><%=  ans.query_id %></td>
                          </tr>
                          <tr>
                              <td style="width: 50%">Solution Provided at </td>
                              <td style="width: 50%"><%=  DateTime.now %></td>
                          </tr>
                       </table>
                          <% end %>
                      </div>
                    </div>
                  </div>
    </div>
<% else %>
<h2><b>We didn't found your Query.Please fetch with some other relevant phrases</b></h2>
<% end %>
<b><%= link_to "Back to Submit Query>>", request.env['HTTP_REFERER'] %></b>